services:
  lint:
    build:
      context: .
      target: dev
    command: ruff check /app
    volumes:
      - ./app:/app
  format:
    build:
      context: .
      target: dev
    command: ruff format /app
    volumes:
      - ./app:/app
  pytest:
    build:
      context: .
      target: dev
    command: python -m pytest /tests -v
    volumes:
      - ./app:/app
      - ./tests:/tests
    working_dir: /app
  run:
    image: wonkyto/techni-metrics-collector:1.1.1
    volumes:
      - ./config:/config
    working_dir: /app
  test:
    image: wonkyto/techni-metrics-collector:1.1.1
    volumes:
      - ./app:/app
      - ./config:/config
    working_dir: /app
